A5PWT_Eshop/A5PWT_Eshop/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using A5PWT_Eshop.Application.ApplicationServices.Products;
using A5PWT_Eshop.Application.ViewModels.Products;
using A5PWT_Eshop.Areas.Admin.Controllers.Common;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace A5PWT_Eshop.Areas.Admin.Controllers
{
    public class ProductsController : AdminController
    {
        private readonly IProductApplicationService _productApplicationService;
        public ProductsController(IProductApplicationService productApplicationService)
        {
            _productApplicationService = productApplicationService;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            
            var vm = _productApplicationService.GetIndexViewModel();
            return View(vm);
        }

        public IActionResult Edit(int id)
        {
            var vm = _productApplicationService.GetProductViewModel(id);
            return View(vm);
        }

        public IActionResult Delete(ProductViewModel model)
        {
            _productApplicationService.Delete(model);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Edit(ProductViewModel model)
        {
            var product = _productApplicationService.Edit(model);
            return Json(product);
        }

        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Insert(ProductViewModel model)
        {
            var product = _productApplicationService.Insert(model);
            return Json(product);
        }

    }
}

A5PWT_Eshop/A5PWT_Eshop/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using A5PWT_Eshop.Application.ApplicationServices.Carts;
using A5PWT_Eshop.Application.ApplicationServices.Security;
using A5PWT_Eshop.Domain.Constants;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace A5PWT_Eshop.Controllers
{
    public class CartsController : Controller
    {
        private readonly ICartApplicationService _cartApplicationService;
        private readonly ISecurityApplicationService _securityApplicationService;

        public CartsController(ICartApplicationService cartApplicationService, ISecurityApplicationService securityApplicationService)
        {
            _cartApplicationService = cartApplicationService;
            _securityApplicationService = securityApplicationService;
        }

        public async Task<IActionResult> Index()
        {
            var vm = _cartApplicationService.GetIndexViewModel(GetOrCreateTrackingCode());
            var user = await _securityApplicationService.GetCurrentUser(User);
            if(user != null)
            {
                vm.UserID = user.Id;
                vm.UserEmail = user.Email;
            }
            return View(vm);
        }

        [HttpPost]
        public JsonResult AddToCart(int id, int amount)
        {
            var cartItem = _cartApplicationService.AddToCart(id, amount, GetOrCreateTrackingCode());
            return Json(cartItem);
        }

        [HttpPost]
        public JsonResult RemoveFromCart(int id)
        {
            _cartApplicationService.RemoveFromCart(id, GetOrCreateTrackingCode());
            return Json("smazáno");
        }

        private string GetOrCreateTrackingCode()
        {
            var utc = Request.Cookies[Cookies.UserTrackingCode];
            if (utc != null)
                return utc;

            var guid = Guid.NewGuid().ToString();
            var options = new CookieOptions();
            options.Expires = DateTime.Now.AddYears(1);
            Response.Cookies.Append(Cookies.UserTrackingCode, guid, options);

            return guid;
        }
    }
}

A5PWT_Eshop/A5PWT_Eshop/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using A5PWT_Eshop.Application.ApplicationServices.Orders;
using A5PWT_Eshop.Application.ApplicationServices.Security;
using A5PWT_Eshop.Domain.Constants;
using Microsoft.AspNetCore.Mvc;

namespace A5PWT_Eshop.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IOrderApplicationService _orderApplicationService;
        private readonly ISecurityApplicationService _securityApplicationService;

        public OrdersController(IOrderApplicationService orderApplicationService, ISecurityApplicationService securityApplicationService)
        {
            _orderApplicationService = orderApplicationService;
            _securityApplicationService = securityApplicationService;
        }
        public async Task<IActionResult> Create()
        {
            var user = await _securityApplicationService.GetCurrentUser(User);

            _orderApplicationService.CreateOrder(user.Id, Request.Cookies[Cookies.UserTrackingCode]);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Index()
        {
            var user = await _securityApplicationService.GetCurrentUser(User);
            var vm = _orderApplicationService.GetIndexViewModel(user.Id);
            return View(vm);
        }
    }
}

A5PWT_Eshop/A5PWT_Eshop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - A5PWT_Eshop</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
              crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container bg-light">
        <nav class="navbar navbar-expand-lg navbar-light mb-0 rounded-0">
            <p class="h3 navbar-brand"><a asp-area="" asp-controller="Products" asp-action="Index">Produkty</a></p>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                <ul class="navbar-nav mr-auto navbar-collapse navbarNav">
                    <li class="nav-link h4">
                        <a asp-area="Admin" asp-controller="Products" asp-action="Index">Admin sekce</a>
                    </li>
                </ul>
                </div>
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2 navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a asp-controller="Carts" asp-action="Index">
                            <i class="fas fa-shopping-cart m-2"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Orders" asp-action="Index">
                            <i class="fas fa-list m-2"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    <div class="container-fluid">
        <div class="container body-content bg-light contentBackground">
            @RenderBody()
            <hr/>
            <footer>
                <p>&copy; 2019 - A5PWT_Eshop</p>
            </footer>
        </div>
    </div>


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>